[build-system]
build-backend = 'setuptools.build_meta'
requires = ['setuptools >= 64.0.0']

[project]
dependencies = ['pydantic>=2.0']
name = 'example-basic'
requires-python = '>=3.11'
version = '0.1.0'

[tool.setuptools.packages.find]
where = ['src']
