[build-system]
build-backend = 'setuptools.build_meta'
requires = ['setuptools >= 64.0.0']

[project]
name = 'example-basic'
version = '0.1.0'
requires-python = '>=3.11'
dependencies = ['pydantic>=2.0']

[tool.setuptools.packages.find]
where = ['src']
